using TMPro;
using UnityEngine;

public class Roulette : MonoBehaviour
{
    #region aditional code

    // The speed of the hamster's rotation in degrees per second
    public float speed = 360f;

    // The amount of energy generated per full rotation in watt-hours
    public float energyPerRotation = 0.5f;

    // The exchange rate of watt-hours to dollars
    public float exchangeRate = 110f;

    // The UI text to display the current money earned
    public TextMeshProUGUI moneyText;

    // The current angle of the hamster's rotation
    private float angle = 0f;

    // The current energy generated by the hamster
    private float energy = 0f;

    // The UI text to display the Energy earned
    public TextMeshProUGUI energyText;

    // The UI text to display the EnergyPerRotation
    public TextMeshProUGUI energyPerRotationText;

    // The current money earned by the hamster
    private float money = 0f;
    private void Awake()
    {
        energyPerRotationText.text = string.Format("${0:0.0}", energyPerRotation);
    }
    #endregion

    public GameEngine GE;
    void Update()
    {
        float amount = Time.time * GE.HSpeed / 4;
        transform.eulerAngles = new Vector3(0, 0, amount * 90);

        #region aditional code

        angle += amount * 90;

        // Wrap the angle around 360 degrees
        angle %= 360f;

        // Check if the hamster has completed a full rotation
        if (angle < GE.HSpeed * Time.deltaTime)
        {
            //Add the energy per rotation to the total energy
            energy += energyPerRotation;
        }

        // Convert the energy to money using the exchange rate
        money = energy * exchangeRate;

        // Update the UI text with the formatted money value
        moneyText.text = string.Format("${0:0.00}", money);
        #endregion

    }
}
